server:
  port: 8089

spring:
  data:
    mongodb:
      uri: mongodb+srv://sayedraja1974_db_user:abdul2004@kindleminds.fl4aefo.mongodb.net/kindleminds?retryWrites=true&w=majority
  application:
    name: kindleminds-backend

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day
